# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-05 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='slug',
        ),
        migrations.AlterField(
            model_name='gallery',
            name='title',
            field=models.CharField(choices=[(b'line_follower', 'Line Follower'), (b'basketball', 'Basketball'), (b'micro_sumo', 'Micro Sumo'), (b'fire_fighhter', 'Fire Fighter'), (b'stair_climbing', 'Stair Climbing'), (b'maze', 'Maze'), (b'color_selecting', 'Color Selecting'), (b'self_balancing', 'Self Balancing'), (b'scenario', 'Scenario'), (b'innovative', 'Innovative'), (b'common', 'About Gallery')], max_length=50),
        ),
    ]
