# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-05 09:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 2, 5, 9, 12, 7, 175891, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
