# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-05 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[(b'about', 'About Us'), (b'categories', 'Categories'), (b'sponsorship', 'Sponsorship'), (b'faq', 'F.A.Q'), (b'contact', 'Contact')], max_length=100)),
                ('subject', models.CharField(blank=True, choices=[(b'general_knowledge', 'General Knowledge and Purposes'), (b'team', 'ITURO Team'), (b'club', 'Control and Automation Club'), (b'past_organizations', 'Past Organizations'), (b'media', 'Media'), (b'gallery', 'Gallery'), (b'line_follower', 'Line Follower'), (b'basketball', 'Basketball'), (b'micro_sumo', 'Micro Sumo'), (b'fire_fighhter', 'Fire Fighter'), (b'stair_climbing', 'Stair Climbing'), (b'maze', 'Maze'), (b'color_selecting', 'Color Selecting'), (b'self_balancing', 'Self Balancing'), (b'scenario', 'Scenario'), (b'innovative', 'Innovative'), (b'category_rules', 'Category Rules'), (b'general_rules', 'General Rules'), (b'our_sponsors', 'Our Sponsors'), (b'past_sponsors', 'Past Sponsors'), (b'about_sponsorship', 'About Sponsorship')], max_length=100, null=True)),
                ('language_code', models.CharField(max_length=2)),
                ('is_public', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryPage',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('page.page',),
        ),
        migrations.CreateModel(
            name='CommonPage',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('page.page',),
        ),
        migrations.CreateModel(
            name='GalleryPage',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('page.page',),
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('page.page',),
        ),
        migrations.CreateModel(
            name='SponsorPage',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('page.page',),
        ),
        migrations.CreateModel(
            name='TeamPage',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('page.page',),
        ),
    ]
