# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-05 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='language_code',
            field=models.CharField(choices=[(b'tr', 'Turkish'), (b'en', 'English')], max_length=2),
        ),
    ]
